// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: proto/user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GreetUser(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error)
	GreetAllUser(ctx context.Context, in *GreetingAllRequest, opts ...grpc.CallOption) (*Greetings, error)
	GreetByID(ctx context.Context, in *GreetingRequestID, opts ...grpc.CallOption) (*GreetingResponseID, error)
	GreetDeleteByID(ctx context.Context, in *GreetingRequestID, opts ...grpc.CallOption) (*GreetingResponse, error)
	GreetUpdate(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GreetUser(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error) {
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GreetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GreetAllUser(ctx context.Context, in *GreetingAllRequest, opts ...grpc.CallOption) (*Greetings, error) {
	out := new(Greetings)
	err := c.cc.Invoke(ctx, "/user.UserService/GreetAllUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GreetByID(ctx context.Context, in *GreetingRequestID, opts ...grpc.CallOption) (*GreetingResponseID, error) {
	out := new(GreetingResponseID)
	err := c.cc.Invoke(ctx, "/user.UserService/GreetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GreetDeleteByID(ctx context.Context, in *GreetingRequestID, opts ...grpc.CallOption) (*GreetingResponse, error) {
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GreetDeleteByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GreetUpdate(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error) {
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GreetUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	GreetUser(context.Context, *GreetingRequest) (*GreetingResponse, error)
	GreetAllUser(context.Context, *GreetingAllRequest) (*Greetings, error)
	GreetByID(context.Context, *GreetingRequestID) (*GreetingResponseID, error)
	GreetDeleteByID(context.Context, *GreetingRequestID) (*GreetingResponse, error)
	GreetUpdate(context.Context, *GreetingRequest) (*GreetingResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) GreetUser(context.Context, *GreetingRequest) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GreetUser not implemented")
}
func (UnimplementedUserServiceServer) GreetAllUser(context.Context, *GreetingAllRequest) (*Greetings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GreetAllUser not implemented")
}
func (UnimplementedUserServiceServer) GreetByID(context.Context, *GreetingRequestID) (*GreetingResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GreetByID not implemented")
}
func (UnimplementedUserServiceServer) GreetDeleteByID(context.Context, *GreetingRequestID) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GreetDeleteByID not implemented")
}
func (UnimplementedUserServiceServer) GreetUpdate(context.Context, *GreetingRequest) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GreetUpdate not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GreetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GreetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GreetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GreetUser(ctx, req.(*GreetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GreetAllUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetingAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GreetAllUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GreetAllUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GreetAllUser(ctx, req.(*GreetingAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GreetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetingRequestID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GreetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GreetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GreetByID(ctx, req.(*GreetingRequestID))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GreetDeleteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetingRequestID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GreetDeleteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GreetDeleteByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GreetDeleteByID(ctx, req.(*GreetingRequestID))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GreetUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GreetUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GreetUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GreetUpdate(ctx, req.(*GreetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GreetUser",
			Handler:    _UserService_GreetUser_Handler,
		},
		{
			MethodName: "GreetAllUser",
			Handler:    _UserService_GreetAllUser_Handler,
		},
		{
			MethodName: "GreetByID",
			Handler:    _UserService_GreetByID_Handler,
		},
		{
			MethodName: "GreetDeleteByID",
			Handler:    _UserService_GreetDeleteByID_Handler,
		},
		{
			MethodName: "GreetUpdate",
			Handler:    _UserService_GreetUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user.proto",
}
